### PR TITLE
update comments using CMIP6 comments where possible

### LINKED ISSUE #20: comment attribute
one more thing to close https://github.com/WCRP-CORDEX/data-request-table/issues/93

> The comment attribute is mostly empty, one could use the comments defined in CMIP6.

We had our own comment column in the data request table but i think we should use the variable comments attribute from CMIP6.

### PR DESCRIPTION
**Pull request by larsbuntemeyer**
closes #20 

uses
```python

import pandas as pd

def retrieve_cmip6_mip_tables():
    """retrieve and concat all cmip6 mip tables from
    https://c6dreq.dkrz.de/docs/CMIP6_MIP_tables.xlsx
    """
    cols = [
        "frequency",
        "modeling_realm",
        "standard_name",
        "units",
        "cell_methods",
        "cell_measures",
        "long_name",
        "comment",
        "dimensions",
        "out_name",
        "type",
        "positive",
        "valid_min",
        "valid_max",
        "ok_min_mean_abs",
        "ok_max_mean_abs",
        "cmip6_table",
    ]
    cmip6_mip_tables_url = "https://c6dreq.dkrz.de/docs/CMIP6_MIP_tables.xlsx"
    tables = pd.read_excel(cmip6_mip_tables_url, sheet_name=None)
    del tables["Notes"]

    def add_table_name(df, table):
        df["cmip6_table"] = table
        return df

    df = pd.concat(add_table_name(df, table) for table, df in tables.items())
    df.rename(
        columns={
            "CF Standard Name": "standard_name",
            "Long name": "long_name",
            "Variable Name": "out_name",
        },
        inplace=True,
    )
    return df[cols].drop_duplicates(ignore_index=True)

df = pd.read_csv("CORDEX-CMIP6/data-request.csv")
cols = df.columns.to_list()

cmip6 = retrieve_cmip6_mip_tables()
cmip6 = cmip6[~cmip6.out_name.isin(["ps", "hus850", "pr", "prc"])] # ps has ambigious comments
cmip6["frequency"] = cmip6.frequency.str.strip('Pt')
cmip6_comments = cmip6.set_index(["out_name", "frequency", "standard_name", "cell_methods", "long_name"])[['comment']]
#cmip6[cmip6.out_name== "hus850"]

pd.set_option('display.max_rows', None)
df = df.set_index(["out_name", "frequency", "standard_name", "cell_methods", "long_name"]).join(cmip6_comments, rsuffix="_cmip6")
df["comment"] = df.comment_cmip6
df = df.drop(columns="comment_cmip6").reset_index()
#df.to_csv()
df[cols].to_csv("CORDEX-CMIP6/data-request.csv", index=False)
```

### CODE REVIEW

**Comment by larsbuntemeyer** [comment]
this needs more investigation...

**Comment by gnikulin** [comment]
Almost all comments describing variables in the original CORDEX DR should be included in the CORDEX-CMIP6 CMOR tables. They better describe different aspects of variables compared to CMIP6. Some of them are based on the CMIP6 tables but with additional explanations. Of course we don't need comments like "daily and monthly means" as for `siconca` and comments about changes.

Would it be possible to copy comments from CMIP6 for all variables that don't have comments right now ?

**Comment by gnikulin** [comment]
if the comment depends on the table, we need to check what table should be used

**Comment by gnikulin** [comment]
Of course, the current comments for `ta50` and `od550aer` must be deleted because they are internal comments not describing the variables.  Here, we can only figure out per variable.

**Comment by larsbuntemeyer** [comment]
I'll close this PR then, i'll have to think of something new...

**Pull request closed without merging**
